# Copyright (c) Anish Acharya.
# Licensed under the MIT License
{
  "seed": 1,
  "train_mode": "distributed",

  "data_config":
  {
    "data_set": "mnist",
    "shape":
    [
        28,
        28
    ],

    "val_frac": 0,
    "num_labels": 10,
    "num_channels": 1,

    "data_sampling_strategy": "iid",
    "num_shards": 80,

    "batch_size": 64,

    "feature_attack_config":
      {
        "noise_model": 'impulse',
        "frac_adv": 0.2,
        "sev": 5,

        # backdoor Attack
        "target_label": 8,
      },
  },

  "training_config":
  {
    "num_clients": 10, # Number of batches in distributed setting
    "client_fraction": 1, # partial device participation - For FL
    "global_epochs": 25, # epochs
    "local_epochs": 1, # local SGD # For FL
    "compute_grad_stats": false,

    "log_freq": "epoch",

    "optimizer_config":
      {
        "client_optimizer_config":
          {
            "optimizer": "Adam",
            "loss": "ce",
            "lr0": 0.01,
            "momentum": 0.9,
            "reg": 0.00001,
            "nesterov": false,
            "amsgrad": false
          },

        "client_lrs_config":
          {
            "lrs": 'cosine',
            "milestones": [1,5,10],
            "step_size": 1,
            "gamma": 0.9
          },

        "server_optimizer_config":
          {
            "optimizer": "SGD",
            "lr0": 1
          }
      },

    "learner_config":
      {
        "net": "small_cnn",
        "mlp_config": { "h1": 300, "h2": 300 }
      },

    "aggregation_config":
      {
        "gar": "mean",

        "geo_med_config": {"alg": 'vardi', 'eps': 0.00001, 'max_iter': 50},
        "trimmed_mean_config":{"proportion": 0.3},
        "krum_config": {"krum_frac": 0.3},
        "norm_clip_config": { "alpha": 0.5},

        "compression_config":
          {
            "compression_operator": None,
            "frac_coordinates_to_keep": 0.5,
            "bits": 2,
            "ef_client": False
          },

        "grad_attack_config":
          {
            "attack_model": None,
            "attack_mode": "un_coordinated",
            "frac_adv": 0.4,
            "rand_additive_attack_conf":
              {
                "noise_dist": "gaussian",
                "mean_shift": 0, "attack_std": 10,   # Gaussian noise
                "noise_range": [ -1, 0 ],             # Uniform noise
              },
            "sign_flip_conf": {"flip_prob": 0.7, "flip_scale": 5},
            "attack_n_std": 1
          },

        "sparse_approximation_config":
          {
            "rule": None,
            "axis": "column",
            "frac_coordinates": 0.2,
            "ef_server": True
          }
      }
  }
}