# Copyright (c) Anish Acharya.
# Licensed under the MIT License
{
  "seed": 1,
  "train_mode": "distributed",

  "data_config": {
    "data_set": "fashion_mnist",
    "shape": [
        28,
        28
    ],

    "num_labels": 10,
    "num_channels": 1,

    "data_sampling_strategy": "iid",
    "num_shards": 80,

    "batch_size": 64,
  },

  "training_config": {
    "num_clients": 32, # Number of batches in distributed setting
    "client_fraction": 1, # partial device participation - For FL
    "global_epochs": 30, # epochs
    "local_epochs": 1, # local SGD # For FL
    "compute_grad_stats": false,

    "optimizer_config":
      {
        "client_optimizer_config":
          {
            "optimizer": "SGD",
            "loss": "ce",
            "lr0": 0.1,
            "momentum": 0.9,
            "reg": 0.0001,
            "nesterov": True,
            "amsgrad": false
          },

        "client_lrs_config":
          {
            "lrs": "step",
            "milestones": [1,5,10],
            "step_size": 1,
            "gamma": 0.9
          },

        "server_optimizer_config":
          {
            "optimizer": "SGD",
            "lr0": 1
          }
      },

    "learner_config":
      {
        "net": "lenet",
        "mlp_config": { "h1": 300, "h2": 300 }
      },

    "aggregation_config":
      {
        "gar": "geo_med",

        "geo_med_config": {"alg": 'vardi', 'eps': 0.00001, 'max_iter': 50},
        "trimmed_mean_config":{"proportion": 0.3},
        "krum_config": {"krum_frac": 0.3},
        "norm_clip_config": { "alpha": 0.5},

        "compression_config":
          {
            "compression_operator": None,
            "frac_coordinates_to_keep": 0.5,
            "bits": 2,
            "ef_client": False
          },

        "attack_config":
          {
            "attack_model": 'random',
            "attack_mode": "un_coordinated",
            "frac_adv": 0.1,
            "rand_additive_attack_conf":
              {
                "noise_dist": "gaussian",
                "mean_shift": 50, "attack_std": 1,   # Gaussian noise
                "noise_range": [ -1, 0 ],             # Uniform noise
              },
            "sign_flip_conf": {"flip_prob": 0.7},
            "attack_n_std": 1
          },

        "sparse_approximation_config":
          {
            "rule": 'active_norm',
            "axis": "column",
            "frac_coordinates": 0.25,
            "ef_server": True
          }
      }
  }
}