{
  "train_mode": "fed",

  "data_config":
    {
      "data_set": "mnist",
      "shape": [28, 28],
      "num_labels": 10,
      "num_channels": 1,
      "download": False,
    },


  "training_config":
    {
      "num_clients": 10,
      "client_fraction": 0.5, # specify fraction of client participation per round

      "batch_size": 32,
      "global_epochs": 1, # Number of communication Rounds
      "local_epochs": 1,

      "optimizer_config":
      {
        "optimizer": 'SGD',
        "loss": 'ce',
        "lr0": 0.001,
        "momentum": 0.9,
        "reg": 0.0001,
        "nesterov": False,
        "amsgrad": False,
      },

      "lrs_config":
      {
        "lrs": None,
        "milestones": [10, 25, 40],
        "step_size": 10,
        "gamma": 0.1
      },

      "compression_config":
      {
        "compression_operator": "full",
        "frac_coordinates_to_keep": 0.5,
      },

      "learner_config":
      {
        "net": "mlp",
      },

      "aggregation_config":
        {
          "gar": "mean",
        },

    },
}